package com.spike.dynamoDB.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "notifications")
public class DynamoDBData {

    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
    private int id;

    @DynamoDBAttribute
    private int cuit;



}
